# Site settings
title: Shane's Material Jekyll
email: shanecooke@mac.com
description: A Material Design inspired Jekyll theme
footer_text: 'Made with <span class="icon-favorite pulse"></span> by <a href="http://joshuaraichur.com">Joshua Raichur</a>. <a href="http://github.com/raichur/material-jekyll">Fork the source.</a>'
baseurl: "/material-jekyll"

# Social usernames
twitter_username: scooke
github_username:  githubber
dribbble_username: scooke
instagram_username: scookeoni
email: shanecooke@mac.com

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exculde: ['.sass_cache', 'README.md']
sass:
  sass_dir: '_assets/_sass'
permalink: "/:title/"

# Defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      is_in_nav: true
